config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'authorss/new'
  get 'authorss/create'
  get 'authorss/update'
  get 'authorss/edit'
  get 'authorss/destroy'
  get 'authorss/index'
  get 'authorss/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/update'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/index'
  get 'categories/show'
  get 'books/new'
  get 'books/create'
  get 'books/update'
  get 'books/edit'
  get 'books/destroy'
  get 'books/index'
  get 'books/show'
  get 'about/index'
  get 'about' => 'about#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'


  resources :books
  resources :authors
  resources :categories
  resources :publishers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :category
    belongs_to :author
    belongs_to :publisher
    
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
    
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = "About this app"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = "Add New Author"
    @author = Author.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = "Add New Book"
    @book = Book.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
    def book_params
      params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :excerpt, :format, :year, :buy, :price, :pages)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = "Add New Category"
    @category = Category.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = "Add New Publisher"
    @publisher = Publisher.new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end

  private
  def publisher_params
    params.require(:publisher).permit(:name)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<div class="well">
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc cursus lacinia orci in tempus. Vivamus euismod ut velit quis finibus. Maecenas dui felis, pharetra et convallis faucibus, tincidunt aliquam est. Nam tincidunt nisl egestas mi tempor, eget aliquet libero egestas. Sed maximus erat vel nibh volutpat aliquam. Maecenas hendrerit finibus enim vel bibendum. Mauris mi sapien, accumsan ut enim hendrerit, pretium molestie dolor. Mauris nec turpis euismod, laoreet augue id, hendrerit libero. Nam ut leo dignissim, rhoncus arcu sodales, volutpat arcu.</p>
</div>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for( @author , remote: true) do |f| %>
     <div class="form-group">
        <%= f.label :first_name %> <br>
        <%= f.text_field (:first_name), class: "form-control" %> <br>
    </div>
    <div class="form-group">
        <%= f.label :last_name %> <br>
        <%= f.text_field (:last_name), class: "form-control" %> <br>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to  "Cancel", authors_path, class: "btn btn-default" %>
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div id="books-index">
    <div class="row">
        <div class="col-md-3 col-sm-3">
            <h3>Ruby on Rails Tutorial</h3>
            <%= image_tag  "ruby_on_rails_tutorial.jpg" %>
            <%= link_to  "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Docker for Rails Developers</h3>
            <%= image_tag  "docker_for_rails_developers.jpg" %>
            <%= link_to  "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Rails Angular Postgres Fullstack Development</h3>
            <%= image_tag  "rails_angular_full_stack.jpg" %>
            <%= link_to  "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>The Ruby Programming Language</h3>
            <%= image_tag  "the_ruby_programming_language.jpg" %>
            <%= link_to  "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 col-sm-3">
            <h3>The Rails 5 Way</h3>
            <%= image_tag  "the_rails_5_way.jpg" %>
            <%= link_to  "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Learn Rails 5</h3>
            <%= image_tag  "learn_rails5.jpg" %>
            <%= link_to  "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Learn Ruby on Rails 5.1</h3>
            <%= image_tag  "learn_ruby_on_rails5.jpg" %>
            <%= link_to  "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
        <div class="col-md-3 col-sm-3">
            <h3>Agile Web Development Rails 5</h3>
            <%= image_tag  "agile_web_dev_rails5.1.jpg" %>
            <%= link_to  "Read More", book_path(1), class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>

<%= form_for( @book, remote: true) do |f| %>
    <div class="form-group">
        <%= f.label :title %> <br>
        <%= f.text_field (:title), class: "form-control" %> <br>
    </div>
    <div class="form-group">
        <%= f.label :isbn %> <br>
        <%= f.text_field (:isbn), class: "form-control" %> <br>
    </div>
    <div class="form-group">
        <%= f.label :category %> <br>
        <%= f.collection_select :category_id, Category.all.collect, :id, :name, {:prompt => true}, {:class => 'form-control dropdown-style'}%> <br><br>
    </div>
    <div class="form-group">
        <%= f.label :author %> <br>
        <%= f.collection_select :author_id, Author.all.collect, :id, :first_name, {:prompt => true}, {:class => 'form-control dropdown-style'} %> <br><br>
    </div>
    <div class="form-group">
        <%= f.label :publisher %> <br>
        <%= f.collection_select :publisher_id, Publisher.all.collect, :id, :name, {:prompt => true},  {:class => 'form-control dropdown-style'} %> <br><br>
    </div>
    <div class="form-group">
        <%= f.label :format %> <br>
        <%= f.text_field (:format), class: "form-control" %> <br>
    </div>
    <div class="form-group">
        <%= f.label :excerpt %> <br>
        <%= f.text_area (:excerpt), class: "form-control" %> <br>
    </div>
    <div class="form-group">
        <%= f.label :pages %> <br>
        <%= f.number_field (:pages), class: "form-control" %> <br>
    </div>
    <div class="form-group">
        <%= f.label :price %> <br>
        <%= f.text_field (:price), class: "form-control" %> <br>
    </div>
    <div class="form-group">
        <%= f.label :buy %> <br>
        <%= f.text_field (:buy), class: "form-control" %> <br>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to  "Cancel", books_path, class: "btn btn-default" %>
<% end %>

app/views/books/show.html.erb
<div class="book-show">
<h2>Ruby on Rails Tutorial</h2>
<div class="books-show-left">
    <%= image_tag  "ruby_on_rails_tutorial.jpg" %></div>
<div class="books-show-right">
    <h3>Book Info</h3>
    <ul>
        <li><strong>Category: </strong>Ruby on Rails</li>
        <li><strong>Author: </strong>Michael Hartl</li>
        <li><strong>Publisher: </strong>Addison-Wesley Professional; 4 edition (November 17, 2016)</li>
        <li><strong>Year: </strong>2016</li>
        <li><strong>ISBN: </strong>978-0134598628</li>
        <li><strong>Format: </strong>Kindle</li>
        <li><strong>Pages: </strong>806</li>
    </ul>
    <%= link_to  "Buy for $31.19", "https://www.amazon.com/Ruby-Rails-Tutorial-Addison-Wesley-Professional-dp-0134598628/dp/0134598628/ref=mt_paperback?_encoding=UTF8&me=&qid=1553783046", id: "select-btn", class: "btn btn-success", target: "blank" %>
</div>
<div class="clearfix"></div>
<h4>Excerpt</h4>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for( @category , remote: true) do |f| %>
     <div class="form-group">
        <%= f.label :name %> <br>
        <%= f.text_field (:name), class: "form-control" %> <br>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to  "Cancel", categories_path, class: "btn btn-default" %>
<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
              <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>
              
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Book', new_book_path %></li>
                  <li><%= link_to 'Category', new_category_path %></li>
                  <li><%= link_to 'Author', new_author_path %></li>
                  <li><%= link_to 'Publisher', new_publisher_path %></li>
                </ul>
              </li>
              </ul>
          </div>
        </div>
      </nav>

      <header>
        <div class="container">
        <h1>The Bookstore <small><%= @page_title ? @page_title : 'Welcome' %></small></h1>
        </div>
      </header>
      <section>
        <div class="container">
          <div class="row">
            <div class="col-md-8">
             <%= yield %>
            </div>
            <div class="col-md-4">
             <%= render "partials/sidebar" %>
            </div>
        </div>
          
        </div>
      </section>

      <footer>
        <div class="container">
          <p>Copyright &copy; 2019 all rights reserved</p>
        </div>
      </footer>
    
  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
<div class="well">
<h3>Location Info</h3>
<ul>
    <li>The BookStore</li>
    <li>Some Address</li>
    <li>Liverpool, NY 13088</li>
    <li>Phone: (315)xxx-xxxx</li>
    <li>Email: support@thebookstore.com</li>
</ul>
</div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
<div class="list-group">
    <a href="#" class="list-group-item">Ruby on Rails</a>
    <a href="#" class="list-group-item">Agile</a>
    <a href="#" class="list-group-item">Web Development</a>
</div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h2>Add New Publisher</h2>

<%= form_for( @publisher , remote: true) do |f| %>
     <div class="form-group">
        <%= f.label :name %> <br>
        <%= f.text_field (:name), class: "form-control" %> <br>
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to  "Cancel", publishers_path, class: "btn btn-default" %>
<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>